apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: finally-pipeline 
  janus-idp.io/tekton: finally-pipeline
  backstage.io/kubernetes-id: finally-pipeline
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: finally-pipeline
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  